# Generated by Django 3.2.3 on 2021-05-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('category1', 'category1'), ('category2', 'category2'), ('category3', 'category3'), ('category4', 'category4')], default='category1', max_length=50),
        ),
    ]
