# Generated by Django 3.2.7 on 2021-09-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210904_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sample1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sample2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sample3',
        ),
    ]
